### ISSUE TITLE
Implement a system to download TAS-focused Gecko Codes

### ISSUE THREAD

**Issue by ximk** [TASLabz/dolphin#44]
The functionality is already there in Dolphin, but how would we create a way to download the recommended gecko codes for TASing through the button?

People have suggested a repository to hold all of the config files, and Dolphin would download and overwrite the current `.ini` file with the new TASing one, but a discussion may be helpful before moving forward.

**Comment by Hibyehello** [comment]
Previous attempt by me for mainstream, would probably work well here https://github.com/dolphin-emu/dolphin/pull/10353

**Comment by malleoz** [comment]
boumi has added the ability to retrieve Gecko Codes from mkwtas.com. Now... How do we set the endpoint to point to mkwtas.com? Do I hard-code it? Should I add a new .ini that associates a mapping between GameIDs and different domains? I don't want to go with Hibyehello's approach because it assumes that other games will be available from that same domain which will not be the case for us.

**Comment by Gaberboo** [comment]
I wouldn't care if you hard code it because I don't care about downloaded codes from the original target Dolphin tries anyway.
